const datosCantabria = {
 "region": "Cantabria",
 "regionSlug": "cantabria",
 "academicYear": "2025/2026",
 "call": "ordinaria",
 "datasetVersion": "2.1-final-depurado-2025-2026",
 "sources": {
  "officialCutsPdf": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
  "supportSite": "https://notasdecorte.es"
 },
 "notes": {
  "groups": {
   "group1": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes",
   "group2": "Titulados universitarios o equivalentes",
   "group3": "Pruebas de acceso para mayores de 25 años",
   "group4": "Mayores de 45",
   "group5": "Mayores de 40 con experiencia profesional",
   "group6": "Bachillerato homologado"
  },
  "annotations": {
   "3": "Último alumno procedente de la misma universidad y con vía preferente",
   "6": "Último alumno procedente de la misma universidad y con vía no preferente",
   "7": "Último alumno admitido con vía preferente y procedente de otra universidad del Distrito Único de Madrid",
   "8": "Último alumno admitido con vía no preferente y procedente de otra universidad del Distrito Único de Madrid",
   "9": "Último alumno admitido con vía preferente y procedente de una universidad pública",
   "10": "Último alumno admitido con vía no preferente y procedente de una universidad pública",
   "11": "Último alumno admitido con vía preferente y procedente de una universidad privada",
   "12": "Último alumno admitido con vía no preferente y procedente de una universidad privada"
  },
  "importantNote": "Versión final depurada del archivo JS de Cantabria, actualizada al curso 2025/2026 y manteniendo la estructura del buscador. Notas (S) y (L) normalizadas a su valor numérico decimal para compatibilidad con el motor de búsqueda."
 },
 "stats": {
  "programCount": 37,
  "programsByUniversity": {
   "Universidad de Cantabria": 37
  },
  "universities": [
   "Universidad de Cantabria"
  ]
 },
 "programs": [
  {
   "id": "cantabria-universidad-de-cantabria-0001-doble-grado-en-administracion-y-direccion-de-empresas-y-economia",
   "code": "0001",
   "officialName": "Doble Grado en Administración y Dirección de Empresas y Economía",
   "displayName": "Doble Grado en Administración y Dirección de Empresas y Economía",
   "officialNameNormalized": "doble grado en administracion y direccion de empresas y economia",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Doble Grado en Administración y Dirección de Empresas y Economía", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 11.787, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "doble grado en administracion y direccion de empresas y economia", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0002-doble-grado-en-admon-y-direccion-de-empresas-y-rel-laborales",
   "code": "0002",
   "officialName": "Doble Grado en Admón. y Dirección de Empresas y Rel. Laborales",
   "displayName": "Doble Grado en Admón. y Dirección de Empresas y Rel. Laborales",
   "officialNameNormalized": "doble grado en adm y direccion de empresas y rel laborales",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Doble Grado en Admón. y Dirección de Empresas y Rel. Laborales", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 9.725, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "doble grado en adm y direccion de empresas y rel laborales", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0003-doble-grado-en-derecho-y-administracion-y-direccion-de-empresas",
   "code": "0003",
   "officialName": "Doble Grado en Derecho y Administración y Dirección de Empresas",
   "displayName": "Doble Grado en Derecho y Administración y Dirección de Empresas",
   "officialNameNormalized": "doble grado en derecho y administracion y direccion de empresas",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Doble Grado en Derecho y Administración y Dirección de Empresas", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 11.150, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "doble grado en derecho y administracion y direccion de empresas", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0004-doble-grado-en-fisica-y-matematicas",
   "code": "0004",
   "officialName": "Doble Grado en Física y Matemáticas",
   "displayName": "Doble Grado en Física y Matemáticas",
   "officialNameNormalized": "doble grado en fisica y matematicas",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias",
   "branchSlug": "ciencias",
   "searchTerms": ["Doble Grado en Física y Matemáticas", "Universidad de Cantabria", "Ciencias"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 13.002, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "doble grado en fisica y matematicas", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0005-doble-grado-en-magisterio-en-educacion-infantil-y-en-educacion-primaria",
   "code": "0005",
   "officialName": "Doble Grado en Magisterio en Educación Infantil y en Educación Primaria",
   "displayName": "Doble Grado en Magisterio en Educación Infantil y en Educación Primaria",
   "officialNameNormalized": "doble grado en magisterio en educacion infantil y en educacion primaria",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Doble Grado en Magisterio en Educación Infantil y en Educación Primaria", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 11.751, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "doble grado en magisterio en educacion infantil y en educacion primaria", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0006-grado-en-administracion-y-direccion-de-empresas",
   "code": "0006",
   "officialName": "Grado en Administración y Dirección de Empresas",
   "displayName": "Grado en Administración y Dirección de Empresas",
   "officialNameNormalized": "grado en administracion y direccion de empresas",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Administración y Dirección de Empresas", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.428, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en administracion y direccion de empresas", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0007-grado-en-ciencias-biomedicas",
   "code": "0007",
   "officialName": "Grado en Ciencias Biomédicas",
   "displayName": "Grado en Ciencias Biomédicas",
   "officialNameNormalized": "grado en ciencias biomedicas",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias",
   "branchSlug": "ciencias",
   "searchTerms": ["Grado en Ciencias Biomédicas", "Universidad de Cantabria", "Ciencias"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 12.524, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ciencias biomedicas", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0008-grado-en-derecho",
   "code": "0008",
   "officialName": "Grado en Derecho",
   "displayName": "Grado en Derecho",
   "officialNameNormalized": "grado en derecho",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Derecho", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 7.593, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en derecho", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0009-grado-en-economia",
   "code": "0009",
   "officialName": "Grado en Economía",
   "displayName": "Grado en Economía",
   "officialNameNormalized": "grado en economia",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Economía", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en economia", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0010-grado-en-economia-itinerario-bilingue",
   "code": "0010",
   "officialName": "Grado en Economía (Itinerario Bilingüe)",
   "displayName": "Grado en Economía (Itinerario Bilingüe)",
   "officialNameNormalized": "grado en economia itinerario bilingue",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Economía (Itinerario Bilingüe)", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 7.822, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en economia itinerario bilingue", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0011-grado-en-enfermeria",
   "code": "0011",
   "officialName": "Grado en Enfermería",
   "displayName": "Grado en Enfermería",
   "officialNameNormalized": "grado en enfermeria",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias de la Salud",
   "branchSlug": "ciencias-de-la-salud",
   "searchTerms": ["Grado en Enfermería", "Universidad de Cantabria", "Ciencias de la Salud"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 11.923, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en enfermeria", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0012-grado-en-estudios-hispanicos",
   "code": "0012",
   "officialName": "Grado en Estudios Hispánicos",
   "displayName": "Grado en Estudios Hispánicos",
   "officialNameNormalized": "grado en estudios hispanicos",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Artes y Humanidades",
   "branchSlug": "artes-y-humanidades",
   "searchTerms": ["Grado en Estudios Hispánicos", "Universidad de Cantabria", "Artes y Humanidades"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en estudios hispanicos", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0013-grado-en-fisica",
   "code": "0013",
   "officialName": "Grado en Física",
   "displayName": "Grado en Física",
   "officialNameNormalized": "grado en fisica",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias",
   "branchSlug": "ciencias",
   "searchTerms": ["Grado en Física", "Universidad de Cantabria", "Ciencias"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 11.120, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en fisica", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0014-grado-en-fisioterapia",
   "code": "0014",
   "officialName": "Grado en Fisioterapia",
   "displayName": "Grado en Fisioterapia",
   "officialNameNormalized": "grado en fisioterapia",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias de la Salud",
   "branchSlug": "ciencias-de-la-salud",
   "searchTerms": ["Grado en Fisioterapia", "Universidad de Cantabria", "Ciencias de la Salud"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 6.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en fisioterapia", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0015-grado-en-geografia-y-ordenacion-del-territorio",
   "code": "0015",
   "officialName": "Grado en Geografía y Ordenación del Territorio",
   "displayName": "Grado en Geografía y Ordenación del Territorio",
   "officialNameNormalized": "grado en geografia y ordenacion del territorio",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Geografía y Ordenación del Territorio", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en geografia y ordenacion del territorio", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0016-grado-en-gestion-hotelera-y-turistica",
   "code": "0016",
   "officialName": "Grado en Gestión Hotelera y Turística",
   "displayName": "Grado en Gestión Hotelera y Turística",
   "officialNameNormalized": "grado en gestion hotelera y turistica",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Gestión Hotelera y Turística", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en gestion hotelera y turistica", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0017-grado-en-historia",
   "code": "0017",
   "officialName": "Grado en Historia",
   "displayName": "Grado en Historia",
   "officialNameNormalized": "grado en historia",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Artes y Humanidades",
   "branchSlug": "artes-y-humanidades",
   "searchTerms": ["Grado en Historia", "Universidad de Cantabria", "Artes y Humanidades"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en historia", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0018-grado-en-ingenieria-civil",
   "code": "0018",
   "officialName": "Grado en Ingeniería Civil",
   "displayName": "Grado en Ingeniería Civil",
   "officialNameNormalized": "grado en ingenieria civil",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Civil", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 7.320, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria civil", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0019-grado-en-ingenieria-civil-itinerario-bilingue",
   "code": "0019",
   "officialName": "Grado en Ingeniería Civil (Itinerario Bilingüe)",
   "displayName": "Grado en Ingeniería Civil (Itinerario Bilingüe)",
   "officialNameNormalized": "grado en ingenieria civil itinerario bilingue",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Civil (Itinerario Bilingüe)", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 11.648, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria civil itinerario bilingue", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0020-grado-en-ingenieria-de-los-recursos-energeticos",
   "code": "0020",
   "officialName": "Grado en Ingeniería de los Recursos Energéticos",
   "displayName": "Grado en Ingeniería de los Recursos Energéticos",
   "officialNameNormalized": "grado en ingenieria de los recursos energeticos",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería de los Recursos Energéticos", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria de los recursos energeticos", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0021-grado-en-ingenieria-de-los-recursos-mineros",
   "code": "0021",
   "officialName": "Grado en Ingeniería de los Recursos Mineros",
   "displayName": "Grado en Ingeniería de los Recursos Mineros",
   "officialNameNormalized": "grado en ingenieria de los recursos mineros",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería de los Recursos Mineros", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria de los recursos mineros", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0022-grado-en-ingenieria-de-tecnologias-de-telecomunicacion",
   "code": "0022",
   "officialName": "Grado en Ingeniería de Tecnologías de Telecomunicación",
   "displayName": "Grado en Ingeniería de Tecnologías de Telecomunicación",
   "officialNameNormalized": "grado en ingenieria de tecnologias de telecomunicacion",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería de Tecnologías de Telecomunicación", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 7.045, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria de tecnologias de telecomunicacion", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0023-grado-en-ingenieria-electrica",
   "code": "0023",
   "officialName": "Grado en Ingeniería Eléctrica",
   "displayName": "Grado en Ingeniería Eléctrica",
   "officialNameNormalized": "grado en ingenieria electrica",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Eléctrica", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria electrica", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0024-grado-en-ingenieria-electronica-industrial-y-automatica",
   "code": "0024",
   "officialName": "Grado en Ingeniería Electrónica Industrial y Automática",
   "displayName": "Grado en Ingeniería Electrónica Industrial y Automática",
   "officialNameNormalized": "grado en ingenieria electronica industrial y automatica",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Electrónica Industrial y Automática", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 9.117, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria electronica industrial y automatica", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0025-grado-en-ingenieria-en-tecnologias-industriales",
   "code": "0025",
   "officialName": "Grado en Ingeniería en Tecnologías Industriales",
   "displayName": "Grado en Ingeniería en Tecnologías Industriales",
   "officialNameNormalized": "grado en ingenieria en tecnologias industriales",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería en Tecnologías Industriales", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 7.921, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria en tecnologias industriales", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0026-grado-en-ingenieria-informatica",
   "code": "0026",
   "officialName": "Grado en Ingeniería Informática",
   "displayName": "Grado en Ingeniería Informática",
   "officialNameNormalized": "grado en ingenieria informatica",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Informática", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 8.991, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria informatica", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0027-grado-en-ingenieria-marina",
   "code": "0027",
   "officialName": "Grado en Ingeniería Marina",
   "displayName": "Grado en Ingeniería Marina",
   "officialNameNormalized": "grado en ingenieria marina",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Marina", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria marina", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0028-grado-en-ingenieria-maritima-y-arquitectura-naval",
   "code": "0028",
   "officialName": "Grado en Ingeniería Marítima y Arquitectura Naval",
   "displayName": "Grado en Ingeniería Marítima y Arquitectura Naval",
   "officialNameNormalized": "grado en ingenieria maritima y arquitectura naval",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Marítima y Arquitectura Naval", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria maritima y arquitectura naval", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0029-grado-en-ingenieria-mecanica",
   "code": "0029",
   "officialName": "Grado en Ingeniería Mecánica",
   "displayName": "Grado en Ingeniería Mecánica",
   "officialNameNormalized": "grado en ingenieria mecanica",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Mecánica", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 8.822, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria mecanica", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0030-grado-en-ingenieria-nautica-y-transporte-maritimo",
   "code": "0030",
   "officialName": "Grado en Ingeniería Náutica y Transporte Marítimo",
   "displayName": "Grado en Ingeniería Náutica y Transporte Marítimo",
   "officialNameNormalized": "grado en ingenieria nautica y transporte maritimo",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Náutica y Transporte Marítimo", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria nautica y transporte maritimo", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0031-grado-en-ingenieria-quimica",
   "code": "0031",
   "officialName": "Grado en Ingeniería Química",
   "displayName": "Grado en Ingeniería Química",
   "officialNameNormalized": "grado en ingenieria quimica",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ingeniería y Arquitectura",
   "branchSlug": "ingenieria-y-arquitectura",
   "searchTerms": ["Grado en Ingeniería Química", "Universidad de Cantabria", "Ingeniería y Arquitectura"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.825, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en ingenieria quimica", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0032-grado-en-logopedia",
   "code": "0032",
   "officialName": "Grado en Logopedia",
   "displayName": "Grado en Logopedia",
   "officialNameNormalized": "grado en logopedia",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias de la Salud",
   "branchSlug": "ciencias-de-la-salud",
   "searchTerms": ["Grado en Logopedia", "Universidad de Cantabria", "Ciencias de la Salud"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en logopedia", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0033-grado-en-magisterio-en-educacion-infantil",
   "code": "0033",
   "officialName": "Grado en Magisterio en Educación Infantil",
   "displayName": "Grado en Magisterio en Educación Infantil",
   "officialNameNormalized": "grado en magisterio en educacion infantil",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Magisterio en Educación Infantil", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 8.671, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en magisterio en educacion infantil", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0034-grado-en-magisterio-en-educacion-primaria",
   "code": "0034",
   "officialName": "Grado en Magisterio en Educación Primaria",
   "displayName": "Grado en Magisterio en Educación Primaria",
   "officialNameNormalized": "grado en magisterio en educacion primaria",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Magisterio en Educación Primaria", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 9.149, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en magisterio en educacion primaria", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0035-grado-en-matematicas",
   "code": "0035",
   "officialName": "Grado en Matemáticas",
   "displayName": "Grado en Matemáticas",
   "officialNameNormalized": "grado en matematicas",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias",
   "branchSlug": "ciencias",
   "searchTerms": ["Grado en Matemáticas", "Universidad de Cantabria", "Ciencias"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 10.338, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en matematicas", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0036-grado-en-medicina",
   "code": "0036",
   "officialName": "Grado en Medicina",
   "displayName": "Grado en Medicina",
   "officialNameNormalized": "grado en medicina",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias de la Salud",
   "branchSlug": "ciencias-de-la-salud",
   "searchTerms": ["Grado en Medicina", "Universidad de Cantabria", "Ciencias de la Salud"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 12.735, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en medicina", "weightingSourceUrl": null}
  },
  {
   "id": "cantabria-universidad-de-cantabria-0037-grado-en-relaciones-laborales",
   "code": "0037",
   "officialName": "Grado en Relaciones Laborales",
   "displayName": "Grado en Relaciones Laborales",
   "officialNameNormalized": "grado en relaciones laborales",
   "university": "Universidad de Cantabria",
   "universitySlug": "universidad-de-cantabria",
   "campus": null,
   "campusSlug": null,
   "branch": "Ciencias Sociales y Jurídicas",
   "branchSlug": "ciencias-sociales-y-juridicas",
   "searchTerms": ["Grado en Relaciones Laborales", "Universidad de Cantabria", "Ciencias Sociales y Jurídicas"],
   "academicYear": "2025/2026",
   "call": "ordinaria",
   "sourceUrl": "https://web.unican.es/notas-de-corte-2025-2026.pdf",
   "accessRecords": [
    {"group": "Grupo 1", "groupKey": "group1", "groupDescription": "Pruebas de acceso a la universidad y equivalentes // Formación Profesional y equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 2", "groupKey": "group2", "groupDescription": "Titulados universitarios o equivalentes", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 3", "groupKey": "group3", "groupDescription": "Pruebas de acceso para mayores de 25 años", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 4", "groupKey": "group4", "groupDescription": "Mayores de 45", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null},
    {"group": "Grupo 5", "groupKey": "group5", "groupDescription": "Mayores de 40 con experiencia profesional", "ordinary": 5.0, "extraordinary": null, "quotaOrRoute": null, "annotationCode": null, "annotationDescription": null}
   ],
   "weightingLink": {"universityKey": null, "degreeNameNormalized": "grado en relaciones laborales", "weightingSourceUrl": null}
  }
 ]
};